# Generated by Django 4.0.4 on 2024-05-23 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atm_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atmcity',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='atmstate',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
